import os
import uuid
import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
)
from reportlab.lib import colors

REPORTS_FOLDER = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "uploads", "reports"
)
if not os.path.exists(REPORTS_FOLDER):
    os.makedirs(REPORTS_FOLDER)


def generate_case_id():
    return "DS-" + datetime.datetime.utcnow().strftime("%Y%m%d") + "-" + str(uuid.uuid4())[:8].upper()


def build_pdf_report(case_id, created_at, combined_result, evidence_details, screenshot_image_path=None):
    filename = f"{case_id}.pdf"
    filepath = os.path.join(REPORTS_FOLDER, filename)

    doc = SimpleDocTemplate(filepath, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Title"], alignment=TA_CENTER, fontSize=20, spaceAfter=6
    )
    heading_style = ParagraphStyle(
        "HeadingStyle", parent=styles["Heading2"], spaceBefore=14, spaceAfter=6, textColor=colors.HexColor("#1e3a8a")
    )
    normal_style = styles["Normal"]

    elements = []

    # Header
    elements.append(Paragraph("DEEP SHIELD", title_style))
    elements.append(Paragraph("Scam Evidence Analysis Report", styles["Heading3"]))
    elements.append(Spacer(1, 12))

    # Case info table
    case_info = [
        ["Case ID", case_id],
        ["Date & Time", created_at],
        ["Overall Risk Level", combined_result.get("overall_level", "N/A")],
        ["Risk Score", f"{combined_result.get('combined_score', 0)}/100"],
        ["Confidence", combined_result.get("confidence", "N/A")],
    ]
    case_table = Table(case_info, colWidths=[5 * cm, 10 * cm])
    case_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f1f5f9")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(case_table)
    elements.append(Spacer(1, 16))

    # Explanation
    elements.append(Paragraph("Analysis Summary", heading_style))
    elements.append(Paragraph(combined_result.get("explanation", "No explanation available"), normal_style))

    # Recommended actions
    elements.append(Paragraph("Recommended Actions", heading_style))
    for action in combined_result.get("recommended_actions", []):
        elements.append(Paragraph(f"• {action}", normal_style))

    # Evidence breakdown
    elements.append(Paragraph("Evidence Breakdown", heading_style))
    for evidence in evidence_details:
        etype = evidence.get("type", "Evidence")
        score = evidence.get("score", 0)
        reasons = evidence.get("reasons", [])

        elements.append(Paragraph(f"<b>{etype} Analysis</b> — Risk Score: {score}/100", normal_style))
        for reason in reasons:
            elements.append(Paragraph(f"&nbsp;&nbsp;- {reason}", normal_style))
        elements.append(Spacer(1, 8))

        # Extra detail fields per evidence type
        if "transcript" in evidence:
            elements.append(Paragraph(f"<i>Transcript:</i> {evidence['transcript']}", normal_style))
            elements.append(Spacer(1, 8))
        if "extracted_text" in evidence:
            elements.append(Paragraph(f"<i>Extracted Text:</i> {evidence['extracted_text']}", normal_style))
            elements.append(Spacer(1, 8))

    # Attach screenshot image if available
    if screenshot_image_path and os.path.exists(screenshot_image_path):
        elements.append(Paragraph("Attached Screenshot Evidence", heading_style))
        try:
            img = RLImage(screenshot_image_path, width=10 * cm, height=None)
            img._restrictSize(10 * cm, 12 * cm)
            elements.append(img)
        except Exception:
            elements.append(Paragraph("(Could not embed image in report)", normal_style))

    elements.append(Spacer(1, 20))
    elements.append(Paragraph(
        "This report was generated by DeepShield for evidence documentation purposes. "
        "It can be attached to a complaint filed on the National Cyber Crime Reporting Portal "
        "(cybercrime.gov.in) or submitted to your local cybercrime cell.",
        ParagraphStyle("Footer", parent=normal_style, fontSize=8, textColor=colors.grey)
    ))

    doc.build(elements)
    return filepath